### ISSUE TITLE
triflejs stop to work if once launch test

### ISSUE THREAD

**Issue by vercha** [xkxin/svg-to-vml-with-trifleJS#1]
Hi, I'd like to know what's your windows2010 SDK 's path? It shut down every time on my machine,.
Thank you.

**Comment by phariel** [comment]
@vercha sorry bro, what did you mean "Windows 2010"? Is that "windows 10"?

**Comment by phariel** [comment]
@vercha I found your issue on triflejs github page:
https://github.com/sdesalas/trifleJS/issues/64

It seems the author hadn't maintained triflejs for a long time.
I suggest you getting rollback for your OS to Windows 7 and try again, it should work perfectly under Windows 7.
